config/routes.rb
Rails.application.routes.draw do
  resources :parks, only: [:show] do
    resources :dinosaurs, only: [:new, :create]
  end

  resources :dinosaurs, only: [:destroy] do
    resources :pockets, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dinosaur.rb
class Dinosaur < ApplicationRecord
  belongs_to :park # @dinosaur.park
  has_many :pockets
  has_many :weapons, through: :pockets # @dinosaur.weapons
  validates :name, presence: true
  # validates :image_url, presence: true
  has_one_attached :photo
end

app/models/park.rb
class Park < ApplicationRecord
  has_many :dinosaurs, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true
end

app/models/pocket.rb
class Pocket < ApplicationRecord
  belongs_to :weapon
  belongs_to :dinosaur
  validates :dinosaur, uniqueness: { scope: :weapon }
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  has_many :pockets
  has_many :dinosaurs, through: :pockets
  validates :name, presence: true, uniqueness: true

  def to_label
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dinosaurs_controller.rb
class DinosaursController < ApplicationController
  def new
    @park = Park.find(params[:park_id])
    @dinosaur = Dinosaur.new
  end

  def create
    @park = Park.find(params[:park_id])
    @dinosaur = Dinosaur.new(dinosaur_params)
    @dinosaur.park = @park
    if @dinosaur.save
      redirect_to park_path(@park)
    else
      render :new
    end
  end

  def destroy
    @dinosaur = Dinosaur.find(params[:id])
    @dinosaur.destroy
    redirect_to park_path(@dinosaur.park)
  end

  private

  def dinosaur_params
    params.require(:dinosaur).permit(:name, :image_url, :photo)
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  def show
    @park = Park.find(params[:id])
  end
end

app/controllers/pockets_controller.rb
class PocketsController < ApplicationController
  def new
    # form
    @dinosaur = Dinosaur.find(params[:dinosaur_id])
    @pocket = Pocket.new
    @weapons = Weapon.order(:name).where.not(id: @dinosaur.weapons)
  end

  def create
    @dinosaur = Dinosaur.find(params[:dinosaur_id])
    @weapons = Weapon.where(id: pocket_params[:weapon_id])
    @weapons.each do |weapon|
      @pocket = Pocket.new(weapon: weapon, dinosaur: @dinosaur)
      @pocket.save
    end
    redirect_to park_path(@dinosaur.park)
    # else
    #   @weapons = Weapon.order(:name).where.not(id: @dinosaur.weapons)
    #   render :new
    # end



  end

  private

  def pocket_params
    params.require(:pocket).permit(weapon_id: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dinosaurs_helper.rb
module DinosaursHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/pockets_helper.rb
module PocketsHelper
end

app/views/dinosaurs/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <h1>Add a Dinosaur to <%= @park.name %></h1>
      <%= simple_form_for [@park, @dinosaur] do |f| %>
        <%= f.input :name %>
        <%#= f.input :image_url %>
        <%= f.input :photo, as: :file %>
        <%= f.submit class: 'btn btn-danger' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JurassicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/parks/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @park.banner_url %>);">
  <div class="container">
    <h1><%= @park.name %></h1>
    <%= link_to new_park_dinosaur_path(@park), class: 'btn btn-success' do %>
      +🦖
    <% end %>
    <!-- <a class="btn btn-flat" href="#">Apply now</a> -->
  </div>
</div>
<div class="container">
  <%= cl_image_tag "b3khrbru0wpy06xtttey.jpg", width: 100, crop: :thumb, gravity: :face %>
</div>
<div class="container">
  <div class="row">
    <div class="col">
      <div class="cards my-5">
        <% @park.dinosaurs.each do |dinosaur| %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= dinosaur.photo.attached? ? cl_image_path(dinosaur.photo.key) : dinosaur.image_url %>)">
            <%= dinosaur.name %>
            <%= link_to dinosaur_path(dinosaur), method: :delete, data: {confirm: "Annihilate #{dinosaur.name}?" }, class: 'card-remove-link' do %>
              <i class="fas fa-meteor"></i>
            <% end %>
            <%= link_to new_dinosaur_pocket_path(dinosaur), class: 'card-pocket-link' do %>
              <i class="fas fa-skull"></i>
            <% end %>
            <div class="card-tags">
              <% dinosaur.weapons.each do |weapon| %>
                <span><%= weapon.name %></span>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pockets/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <h1>Arm <%= @dinosaur.name %></h1>
      <%= simple_form_for [@dinosaur, @pocket] do |f| %>
        <%= f.association :weapon, collection: @weapons, include_blank: false, include_hidden: false, input_html: { multiple: true, class: 'select2' } %>
        <%= f.submit class: 'btn btn-danger' %>
      <% end %>
    </div>
  </div>
</div>